name: build
on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: homerun_ratings
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"
          cache-dependency-path: |
            rating-service/go.sum
            notification-service/go.sum

      - name: Set up path
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go work sync
          go mod download

      - name: Build
        run: make build

      - name: Test
        env:
          APP_DSN: postgresql://postgres:postgres@localhost:5432/homerun_ratings?sslmode=disable
        run: |
          make db-migrate
          make test